implement TBB
embedded-dev-research/itlab_2023 pull request #105
Opened 2024-03-25 17:10 UTC by Semyon1104

2024-03-27 18:05 UTC, Semyon1104 commented
> I don't see cmake scripts for tbb (stage - build for onetbb)

just add to cmake script as googletest and link tbb in tests? or build like opencv?

2024-03-29 10:52 UTC, allnes commented
After looked at win build, I see we need to use way same as opencv and disable tbb tests

2024-05-11 10:35 UTC, aobolensk requested changes

2024-05-11 10:35 UTC, aobolensk commented on 3rdparty/CMakeLists.txt
> +add_subdirectory(TBB)
```suggestion
add_subdirectory(TBB)

```

2024-05-11 10:35 UTC, aobolensk commented on app/CMakeLists.txt
> +        else()
```suggestion
    else()
```

2024-05-11 10:36 UTC, aobolensk approved these changes

2024-05-12 07:46 UTC, merged