Add parameters to EWLayer
embedded-dev-research/itlab_2023 pull request #114
Opened 2024-04-10 14:01 UTC by NeiroYT

2024-04-11 00:15 UTC, aobolensk requested changes

2024-04-11 00:15 UTC, aobolensk commented on include/layers/EWLayer.hpp
>  }
Functions with such name should not be a part of the library

2024-04-12 15:13 UTC, aobolensk commented on include/layers/EWLayer.hpp
> +    std::transform(input.begin(), input.end(), res.begin(), mysin<ValueType>);
```suggestion
    std::transform(input.begin(), input.end(), res.begin(), [](ValueType input) {return static_cast<T>(std::sin(input));});
```

2024-04-13 15:56 UTC, aobolensk approved these changes
LGTM! Please, resolve merge conflicts to proceed

2024-04-13 20:59 UTC, allnes approved these changes

2024-04-19 12:02 UTC, merged