Introduce the namespace for the library
embedded-dev-research/itlab_2023 pull request #118
Opened 2024-04-25 17:11 UTC by Semyon1104

2024-04-25 17:14 UTC, Semyon1104 commented
This branch is branched off from a branch that hasn't been merged yet - Move alexnet_src.cpp and reader_img.cpp to app directory

2024-04-26 05:44 UTC, aobolensk commented
> This branch is branched off from a branch that hasn't been merged yet - Move alexnet_src.cpp and reader_img.cpp to app directory

You may update your branch now. https://github.com/embedded-dev-research/itlab_2023/pull/111 has been merged

2024-04-26 13:19 UTC, aobolensk requested changes

2024-04-26 13:19 UTC, aobolensk commented on include/layers/ConvLayer.hpp
> +}  // namespace itlab_2023
```suggestion
}  // namespace itlab_2023

```

2024-04-26 13:19 UTC, aobolensk commented on include/layers/Layer.hpp
> +}  // namespace itlab_2023
```suggestion
}  // namespace itlab_2023

```

2024-04-26 13:19 UTC, aobolensk commented on src/layers/ConvLayer.cpp
> +}  // namespace itlab_2023
```suggestion
}  // namespace itlab_2023

```

2024-04-26 13:21 UTC, aobolensk approved these changes

2024-04-26 13:22 UTC, merged