Add Bias to Tensor
embedded-dev-research/itlab_2023 pull request #149
Opened 2024-07-09 16:50 UTC by Semyon1104

2024-07-09 16:52 UTC, Semyon1104 commented
Please look at the changes in the tensor, so that I understand whether it is worth changing the rest of the layers based on it or not?

2024-07-12 16:41 UTC, aobolensk requested changes

2024-07-12 16:41 UTC, aobolensk commented on include/layers/ConvLayer.hpp
> +                     const Tensor& bias = Tensor())  // bias �� ���������
Please fix the comments

2024-07-12 16:41 UTC, aobolensk commented on include/layers/Tensor.hpp
> -
Why it was removed?

2024-07-12 16:41 UTC, aobolensk commented on src/layers/ConvLayer.cpp
> +}  // namespace itlab_2023
```suggestion
}  // namespace itlab_2023

```

2024-07-12 16:41 UTC, aobolensk commented on src/layers/Tensor.cpp
> +
Remove

2024-07-19 14:34 UTC, aobolensk commented on include/layers/Tensor.hpp
> +    if (bias.size() != shape_[1]) {
I guess, we need to check if shape_[1] exists before (check for shape.size())

2024-07-19 14:34 UTC, aobolensk commented on include/layers/Tensor.hpp
> +    return total_size;
Consider using std::accumulate

2024-07-26 14:32 UTC, aobolensk approved these changes

2024-08-03 03:37 UTC, merged