Fix timer accuracy test
embedded-dev-research/itlab_2023 pull request #31
Opened 2023-12-10 20:23 UTC by NeiroYT

https://github.com/embedded-dev-research/itlab_2023/issues/30

2023-12-11 01:18 UTC, aobolensk requested changes
In these case tests do not check "nearly correct time". We can either rename these tests or just raise upper bound in EXPECT_GE

2023-12-11 20:27 UTC, NeiroYT commented
Changed to +1000 ms upper bound

2023-12-11 23:43 UTC, aobolensk approved these changes

2023-12-12 00:48 UTC, allnes approved these changes

2023-12-12 15:54 UTC, AndreySorokin7 approved these changes

2023-12-12 15:54 UTC, merged