add tensorflow dependency
embedded-dev-research/itlab_2023 pull request #58
Opened 2024-02-12 17:38 UTC by Semyon1104

fix #19

2024-02-15 04:50 UTC, aobolensk requested changes

2024-02-15 04:50 UTC, aobolensk commented on include/alexnet/alexnet.hpp
> +#include <iostream>
Move them to cpp file

2024-02-15 04:50 UTC, aobolensk commented on include/alexnet/CMakeLists.txt
> +set(TENSORFLOW_ROOT "/home/osboxes/.local/lib/python3.6/site-packages/tensorflow")
This path is hardcoded and will not work on other machines

2024-02-16 14:16 UTC, Semyon1104 commented on include/alexnet/alexnet.hpp
> +#include <iostream>
remove the hpp file?

2024-03-01 23:37 UTC, allnes commented
@Semyon1104 please resolve conflicts

2024-03-15 18:05 UTC, allnes approved these changes

2024-03-22 15:23 UTC, aobolensk requested changes

2024-03-22 15:23 UTC, aobolensk commented on test/CMakeLists.txt
> +add_definitions(-DMODEL_PATH="${CMAKE_CURRENT_BINARY_DIR}/squeeze.tflite")
```suggestion
add_definitions(-DMODEL_PATH="${CMAKE_CURRENT_BINARY_DIR}/squeeze.tflite")

```

2024-03-22 15:23 UTC, aobolensk commented on test/model_read/model_read.cpp
> +}
```suggestion
}

```

2024-03-22 15:23 UTC, aobolensk commented on include/alexnet/CMakeLists.txt
> +    #message("TensorFlow_LIBRARIES: ${TensorFlow_LIBRARIES}")
```suggestion
```

2024-03-22 15:29 UTC, aobolensk approved these changes

2024-03-22 15:54 UTC, merged