Implement Convolution Layer
embedded-dev-research/itlab_2023 pull request #89
Opened 2024-03-21 20:28 UTC by AndreySorokin7

Close #10

2024-03-24 19:32 UTC, NeiroYT requested changes

2024-03-24 19:32 UTC, NeiroYT commented on include/layers/ConvLayer.hpp
> +  int input_width = static_cast<int>(std::sqrt(input_size / 3));
This doesn't make sense if you can work with shapes, make kernel tensor, and input  have its shape

2024-03-24 19:32 UTC, NeiroYT commented on include/layers/ConvLayer.hpp
> +       i < static_cast<int>(input_size / 3); i += static_cast<int>(step_)) {
Is it better to find center instead of left-top corner?

2024-03-24 19:32 UTC, NeiroYT commented on include/layers/ConvLayer.hpp
> +             (3 - static_cast<int>(step_));
I can't understand this without comments

2024-03-26 17:17 UTC, aobolensk requested changes

2024-03-26 17:17 UTC, aobolensk commented on include/layers/ConvLayer.hpp
> +  ConvolutionalLayer() = default;
Missing parameters:
- stride
- pads (horizontal, vertical)
- dilations

2024-03-26 17:17 UTC, aobolensk commented on include/layers/ConvLayer.hpp
> +      size_t kernel_size = kernel_.get_shape()[kernel_.get_shape().dims() - 1];
Need to add checks if there are enough dims for that

2024-04-06 02:07 UTC, NeiroYT commented on include/layers/ConvLayer.hpp
> +void ConvolutionalLayer::run(const Tensor& input, Tensor& output,
you can move run function to cpp file

2024-04-06 13:50 UTC, NeiroYT commented on include/layers/ConvLayer.hpp
> +void emplConv(const Tensor& input, Tensor& output, const Tensor& kernel_,
`ConvImpl`, implementation

2024-04-19 12:07 UTC, allnes approved these changes

2024-04-19 14:47 UTC, aobolensk commented on include/layers/ConvLayer.hpp
> +void emplConv(const Tensor& input, Tensor& output, const Tensor& kernel_,
Please, follow up this

2024-04-19 14:47 UTC, aobolensk approved these changes

2024-04-26 04:19 UTC, NeiroYT approved these changes
4 tests are not enough i think, but i guess it can be fixed later with parameterized tests

2024-04-26 05:41 UTC, aobolensk commented
> 4 tests are not enough i think, but i guess it can be fixed later with parameterized tests

I agree here

2024-04-26 05:42 UTC, merged